### PR TITLE
Caton intake ch 4-5

### PR DESCRIPTION
**Pull request by juliegugge**
@jaredh159 @Henderjay

### CODE REVIEW

**Comment by juliegugge** [comment]
Some things to note: There is a section in the modern chapter that's grayed out but shows on preview. It happened when I changed Luke's Collection of writings... Wait... I just looked and the letters are white again. Ok so that appears to be ok. Some things... I'm noticing end brackets that aren't escaped, so I'm changing them. Is it unnecessary to escape them in all situations? And the lines that say "Returning to journal" have a blank line after them, but in the preview there is no blank line. Also, I couldn't decided what type of embedded document I should use for the part that talked about Luke Howard. It was partly legal but written by Friends in Kent... I think I chose legal...

**Comment by juliegugge** [comment]
oh and chapter 4 was much longer than 1,2 and 3, so I am doing 5 separately.

**Comment by juliegugge** [comment]
And I forgot, but one of the signatures still has a dash in front of it, but it's not there in the asciidoc text... It's a 'signed signature close' I think... You said not to put dashes in front of signatures....?

**Comment by jaredh159** [comment]
Thanks Julie, lots of good work here. I made note of some more of the modernization changes you did, because I liked them and might try to apply some of them across other documents, so thanks!

About the end brackets, in some cases they don't need to be escaped, but escaping them doesn't break anything, and probably makes it more clear, so I like that you escaped them, and we'll leave them that way.

About the returning to journal lines... I'm not sure.  After I get all these merged in I'm going to do a little bit of poking around on this document and tweak a few things, so I'll try to figure out how to handle those when I do that work.

**Pull request merged**
